In [1]:
import tensorflow as tf
from tensorflow import keras
print(tf.__version__)

2.0.0


In [2]:
import keras
import numpy as np

Using TensorFlow backend.


In [3]:
model=keras.Sequential([keras.layers.Dense(units=1,input_shape=[1])])
model.compile(optimizer='sgd',loss='mean_squared_error')

In [4]:
x=np.array([-3,0,2,3,4,-8])
y=np.array([2,3,4,57,0,1])

In [5]:
model.predict([10.0])

array([[11.687261]], dtype=float32)

In [6]:
#fashion mnist data
mnist=tf.keras.datasets.fashion_mnist

In [7]:
(training_images,training_labels),(test_images,test_labels)=mnist.load_data()

In [8]:
import matplotlib.pyplot as plt
plt.imshow(training_images[0])
print(training_labels[0])
print(training_images[0])

9
[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   1   0   0  13  73   0
    0   1   4   0   0   0   0   1   1   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   3   0  36 136 127  62
   54   0   0   0   1   3   4   0   0   3]
 [  0   0   0   0   0   0   0   0   0   0   0   0   6   0 102 204 176 134
  144 123  23   0   0   0   0  12  10   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0 155 236 207 178
  107 156 161 109  64  23  77 130  72  15]
 [  0   0   0   0   0   0   0   0   0   0   0   1   0  69 207 223 218 216
  216 163 127 121 122 146 141  88 172  66]
 [  0   0   0   0   0   0   0   0   0   1   1   1   0 200 232 

In [9]:
model=keras.Sequential([keras.layers.Flatten(input_shape=(28,28)),
                        keras.layers.Dense(128,activation='relu'),
                       keras.layers.Dense(10,activation='softmax')])

In [10]:
training_images=training_images/255.0
test_images=test_images/255.0

In [11]:
model=tf.keras.models.Sequential([tf.keras.layers.Flatten(),
                          tf.keras.layers.Dense(128,activation=tf.nn.relu),
                          tf.keras.layers.Dense(10,activation=tf.nn.softmax)])

In [12]:
model.compile(optimizer='adam',
             loss='sparse_categorical_crossentropy',
             metrics=['accuracy'])

In [13]:
model.fit(training_images,training_labels,epochs=10)
model.predict(test_images)
model.evaluate(test_images,test_labels)


Train on 60000 samples
Epoch 1/10
60000/60000 [==============================] - 20s 336us/sample - loss: 0.5007 - accuracy: 0.8241
Epoch 2/10
60000/60000 [==============================] - 11s 185us/sample - loss: 0.3747 - accuracy: 0.8662
Epoch 3/10
60000/60000 [==============================] - 7s 112us/sample - loss: 0.3369 - accuracy: 0.8791
Epoch 4/10
60000/60000 [==============================] - 8s 133us/sample - loss: 0.3125 - accuracy: 0.8862
Epoch 5/10
60000/60000 [==============================] - 7s 111us/sample - loss: 0.2938 - accuracy: 0.8914
Epoch 6/10
60000/60000 [==============================] - 6s 100us/sample - loss: 0.2799 - accuracy: 0.8963
Epoch 7/10
60000/60000 [==============================] - 6s 92us/sample - loss: 0.2701 - accuracy: 0.9000
Epoch 8/10
60000/60000 [==============================] - 6s 97us/sample - loss: 0.2602 - accuracy: 0.9035
Epoch 9/10
60000/60000 [==============================] - 5s 89us/sample - loss: 0.2484 - accuracy: 0.9077
Epoch 

[0.3265610898375511, 0.8875]

In [14]:
pred=model.predict(test_images)
print(pred[0])
print(test_labels[0])

[2.7662309e-06 5.0634340e-11 3.3922316e-08 1.2404937e-10 2.8529573e-08
 9.6517215e-03 4.9591574e-07 2.0387294e-02 9.5257874e-08 9.6995753e-01]
9


In [15]:
model=tf.keras.models.Sequential([tf.keras.layers.Flatten(),
                          tf.keras.layers.Dense(128,activation=tf.nn.relu),
                          tf.keras.layers.Dense(512,activation=tf.nn.relu),
                          tf.keras.layers.Dense(10,activation=tf.nn.softmax)])

In [16]:
model.compile(optimizer='adam',
             loss='sparse_categorical_crossentropy',
             metrics=['accuracy'])

In [17]:
model.fit(training_images,training_labels,epochs=10)
model.predict(test_images)
model.evaluate(test_images,test_labels)


Train on 60000 samples
Epoch 1/10
60000/60000 [==============================] - 16s 270us/sample - loss: 0.4754 - accuracy: 0.8292
Epoch 2/10
60000/60000 [==============================] - 11s 177us/sample - loss: 0.3568 - accuracy: 0.8690
Epoch 3/10
60000/60000 [==============================] - 10s 161us/sample - loss: 0.3245 - accuracy: 0.8801
Epoch 4/10
60000/60000 [==============================] - 10s 163us/sample - loss: 0.3015 - accuracy: 0.8891
Epoch 5/10
60000/60000 [==============================] - 9s 158us/sample - loss: 0.2863 - accuracy: 0.8918
Epoch 6/10
60000/60000 [==============================] - 9s 144us/sample - loss: 0.2703 - accuracy: 0.8986
Epoch 7/10
60000/60000 [==============================] - 8s 132us/sample - loss: 0.2573 - accuracy: 0.9028
Epoch 8/10
60000/60000 [==============================] - 8s 134us/sample - loss: 0.2467 - accuracy: 0.9067
Epoch 9/10
60000/60000 [==============================] - 8s 128us/sample - loss: 0.2364 - accuracy: 0.9109
E

[0.34896848504543304, 0.8791]

In [18]:
pred=model.predict(test_images)
print(pred[0])
print(test_labels[0])

[5.0905435e-10 1.3582955e-07 7.0724959e-10 2.5922064e-10 1.5812771e-11
 7.3548222e-06 2.9237329e-10 1.0278594e-03 3.9528558e-09 9.9896467e-01]
9


In [19]:
model=tf.keras.models.Sequential([tf.keras.layers.Flatten(),
                          tf.keras.layers.Dense(64,activation=tf.nn.relu),
                          tf.keras.layers.Dense(64,activation=tf.nn.relu),
                          tf.keras.layers.Dense(10,activation=tf.nn.softmax)])

In [20]:
model.compile(optimizer='sgd',
             loss='sparse_categorical_crossentropy',
             metrics=['accuracy'])

In [21]:
model.fit(training_images,training_labels,epochs=10)

Train on 60000 samples
Epoch 1/10
60000/60000 [==============================] - 12s 204us/sample - loss: 0.7801 - accuracy: 0.7417
Epoch 2/10
60000/60000 [==============================] - 8s 131us/sample - loss: 0.5069 - accuracy: 0.8250
Epoch 3/10
60000/60000 [==============================] - 7s 115us/sample - loss: 0.4598 - accuracy: 0.8389
Epoch 4/10
60000/60000 [==============================] - 5s 84us/sample - loss: 0.4324 - accuracy: 0.8491
Epoch 5/10
60000/60000 [==============================] - 6s 93us/sample - loss: 0.4136 - accuracy: 0.8549
Epoch 6/10
60000/60000 [==============================] - 5s 80us/sample - loss: 0.3984 - accuracy: 0.8609
Epoch 7/10
60000/60000 [==============================] - 5s 80us/sample - loss: 0.3851 - accuracy: 0.8650
Epoch 8/10
60000/60000 [==============================] - 5s 79us/sample - loss: 0.3737 - accuracy: 0.8688
Epoch 9/10
60000/60000 [==============================] - 5s 79us/sample - loss: 0.3641 - accuracy: 0.8719
Epoch 10/1

In [22]:
model.predict(test_images)

array([[7.4045631e-05, 3.9282138e-08, 3.5945463e-06, ..., 6.9895089e-02,
        9.7258308e-04, 8.7422580e-01],
       [1.6598510e-04, 5.2948481e-06, 9.8409539e-01, ..., 2.6812911e-11,
        3.6948561e-06, 2.3406541e-11],
       [1.3901962e-05, 9.9995673e-01, 1.4350063e-06, ..., 1.5897110e-09,
        2.3775083e-08, 2.9994900e-12],
       ...,
       [2.2900758e-02, 1.1266505e-05, 3.3948214e-03, ..., 2.0361373e-05,
        9.5399863e-01, 3.7341982e-07],
       [4.2990032e-06, 9.9972993e-01, 2.6436787e-06, ..., 4.8504620e-07,
        1.2648324e-07, 6.2288108e-09],
       [5.5148586e-04, 1.3119727e-04, 3.0414984e-04, ..., 3.1641040e-02,
        6.7238891e-03, 7.9338113e-04]], dtype=float32)

In [23]:
model.evaluate(test_images,test_labels)

10000/1 [===============================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[0.3948474164009094, 0.8612]

In [25]:
model=tf.keras.models.Sequential([tf.keras.layers.Flatten(),
                          tf.keras.layers.Dense(64,activation=tf.nn.relu),
                          tf.keras.layers.Dense(64,activation=tf.nn.relu),
                          tf.keras.layers.Dense(32,activation=tf.nn.relu),
                          tf.keras.layers.Dense(10,activation=tf.nn.softmax)])

In [27]:
model.compile(optimizer='sgd',
             loss='sparse_categorical_crossentropy',
             metrics=['accuracy'])

In [28]:
model.fit(training_images,training_labels,epochs=20)

Train on 60000 samples
Epoch 1/20
60000/60000 [==============================] - 16s 261us/sample - loss: 0.8152 - accuracy: 0.7248
Epoch 2/20
60000/60000 [==============================] - 9s 145us/sample - loss: 0.4978 - accuracy: 0.8240
Epoch 3/20
60000/60000 [==============================] - 7s 114us/sample - loss: 0.4483 - accuracy: 0.8416
Epoch 4/20
60000/60000 [==============================] - 6s 101us/sample - loss: 0.4204 - accuracy: 0.8520
Epoch 5/20
60000/60000 [==============================] - 6s 95us/sample - loss: 0.3994 - accuracy: 0.8590
Epoch 6/20
60000/60000 [==============================] - 5s 82us/sample - loss: 0.3829 - accuracy: 0.8623
Epoch 7/20
60000/60000 [==============================] - 5s 82us/sample - loss: 0.3693 - accuracy: 0.8682
Epoch 8/20
60000/60000 [==============================] - 5s 83us/sample - loss: 0.3568 - accuracy: 0.8707
Epoch 9/20
60000/60000 [==============================] - 6s 97us/sample - loss: 0.3464 - accuracy: 0.8750
Epoch 10/

In [29]:
model.predict(test_images)

array([[1.05210711e-05, 5.69307758e-06, 2.50056672e-07, ...,
        1.06355278e-02, 1.02541824e-04, 9.74903882e-01],
       [1.84979272e-05, 8.00197881e-08, 9.98650610e-01, ...,
        7.24617877e-08, 5.40707212e-08, 9.54953391e-12],
       [2.00064869e-06, 9.99993086e-01, 1.68920690e-06, ...,
        3.25945209e-08, 4.57182603e-09, 1.44197344e-07],
       ...,
       [1.11058122e-02, 3.27633825e-05, 7.51183182e-03, ...,
        1.08018676e-05, 9.68244195e-01, 2.49872892e-06],
       [1.11384797e-05, 9.99507904e-01, 3.00027677e-05, ...,
        9.26510836e-07, 1.06005942e-07, 8.20447099e-07],
       [1.14699644e-04, 9.97663165e-07, 3.18822131e-05, ...,
        9.89610516e-03, 6.28561305e-04, 3.77239994e-05]], dtype=float32)

In [30]:
model.evaluate(test_images,test_labels)

10000/1 [===============================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[0.35144616792201994, 0.8748]